version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/docker-volumes/jenkins_home:/var/jenkins_home
    networks:
      - net

  search-lambda:
    container_name: search-lambda
    image: search-image
    build:
      context: $PWD
    ports:
      - "3000:3000"
    networks:
      - net

networks:
  net:
